import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-background text-foreground font-galmuri flex flex-col items-center">
        <div className="w-full max-w-[840px] px-6 min-h-screen pt-2 md:pt-10">
          {children}
        </div>
      </body>
    </html>
  );
}
